'use strict';

// ---------------------------------------------------------------------------
// Character sprites, hand-drawn as pixel maps and assembled programmatically:
//   front (facing SW/SE) + back (facing NE/NW), mirrored for left/right.
//   Walk cycles are generated by leg surgery on the base maps.
// Legend:
//   o outline   h hair    H hair-light  d hair-dark  r hair clip
//   s skin      S shadow  e eye         b blush      m mouth
//   w white     t dress   T dress-lite  u dress-dark
//   l leg       k shoe
// ---------------------------------------------------------------------------

const ActorSprites = (() => {

  const LEGEND = {
    o: PAL.outline,
    h: PAL.hair, H: PAL.hairLite, d: PAL.hairDark, r: '#d8626d',
    s: PAL.skin, S: PAL.skinDark, e: '#3a2c33', b: '#efa08d', m: '#c4695e',
    w: '#fdf7e8', t: '#d98a7e', T: '#edb3a2', u: '#a95f5c',
    l: PAL.skin, k: '#7a4a3a',
  };

  const FRONT = [
    '....oooooo....',
    '...ohhhhhho...',
    '..ohhhhhhhho..',
    '..ohHhhhhHho..',
    '..ohhhhhhrho..',
    '..ohshsshsho..',
    '..ohssssssho..',
    '..ohsessesho..',
    '..ohbssssbho..',
    '..ohssmsssho..',
    '...ohssssho...',
    '.....oSSo.....',
    '...owttttwo...',
    '..osttttttso..',
    '..osttutttso..',
    '..oSttttttSo..',
    '..otttttttto..',
    '.otttuttuttto.',
    '.ouuuuuuuuuuo.',
    '....ll..ll....',
    '....ll..ll....',
    '....ww..ww....',
    '....kk..kk....',
  ];

  const BACK = [
    '....oooooo....',
    '...ohhhhhho...',
    '..ohhhhhhhho..',
    '..ohHhhhhhho..',
    '..ohhhhhhhho..',
    '..ohhhhhhhho..',
    '..ohhdhhhhho..',
    '..ohhhhhdhho..',
    '..ohhhhhhhho..',
    '..ohhhhhhhho..',
    '...ohhhhhho...',
    '.....oSSo.....',
    '...otttttto...',
    '..osttttttso..',
    '..osttttttso..',
    '..oSttttttSo..',
    '..otttttttto..',
    '.otttttttttto.',
    '.ouuuuuuuuuuo.',
    '....ll..ll....',
    '....ll..ll....',
    '....ww..ww....',
    '....kk..kk....',
  ];

  const LEG_ROWS = [19, 20, 21, 22];
  const LEFT_LEG = [4, 5], RIGHT_LEG = [8, 9];

  function setChars(rows, row, cols, ch) {
    const chars = rows[row].split('');
    for (const c of cols) chars[c] = ch;
    rows[row] = chars.join('');
  }

  function clone(rows) { return rows.slice(); }

  // Lift one leg: clear its lowest row and raise the shoe by one row.
  function stepFrame(base, liftedCols) {
    const rows = clone(base);
    setChars(rows, 22, liftedCols, '.');
    setChars(rows, 21, liftedCols, 'k');
    setChars(rows, 20, liftedCols, 'w');
    return rows;
  }

  function blinkFrame(base) {
    const rows = clone(base);
    rows[7] = rows[7].replace(/e/g, 'S');
    return rows;
  }

  // Seated: keep rows 0..18 (head + dress), then short bent legs.
  function seatedFrame(base) {
    const rows = base.slice(0, 19);
    rows.push('....ll..ll....');
    rows.push('....kk..kk....');
    return rows;
  }

  function bake(rows) { return Surface.fromMap(rows, LEGEND); }

  // --- AI chibi frames (route 2) -------------------------------------------
  // assets/ai/actor/manifest.json lists frames produced by tools/make_actor.py.
  // When the full set is present, build() swaps the procedural maps for them;
  // otherwise the hand-drawn pixel maps above remain the fallback.

  const AI_FRAMES = {};
  const AI_REQUIRED = ['front-stand', 'front-stride', 'front-sit',
                       'back-stand', 'back-stride', 'back-sit'];

  async function loadOverrides(url = 'assets/ai/actor/manifest.json') {
    try {
      const res = await fetch(url, { cache: 'no-store' });
      if (!res.ok) return;
      const manifest = await res.json();
      await Promise.all(Object.entries(manifest).map(([name, meta]) => new Promise(resolve => {
        const img = new Image();
        img.onload = () => {
          const sf = new Surface(img.width, img.height);
          sf.ctx.drawImage(img, 0, 0);
          AI_FRAMES[name] = sf;
          resolve();
        };
        img.onerror = () => resolve();
        img.src = `${meta.url}?t=${Date.now()}`;
      })));
    } catch (err) {
      console.warn('actor sprite overrides unavailable', err);
    }
  }

  function aiDir(stand, stride, sit) {
    return { stand, blink: stand, walk: [stand, stride], sit };
  }

  function buildFromAI() {
    const F = AI_FRAMES;
    const dirs = {
      downLeft: aiDir(F['front-stand'], F['front-stride'], F['front-sit']),
      upRight: aiDir(F['back-stand'], F['back-stride'], F['back-sit']),
    };
    dirs.downRight = mirrorDir(dirs.downLeft);
    dirs.upLeft = mirrorDir(dirs.upRight);
    return {
      dirs, sleepHead: bakeSleepHead(),
      height: F['front-stand'].h, sitHeight: F['front-sit'].h,
      // px the seated frame sinks below the seat-top anchor, per facing
      sitDrop: { downLeft: 7, downRight: 7, upRight: 4, upLeft: 4 },
    };
  }

  // Side sleeping head: drawn to lie on the bed pillow, body under duvet.
  function bakeSleepHead() {
    const rows = [
      '..oooooo..',
      '.ohhhhhho.',
      'ohhhhhhhho',
      'ohHhhhhhho',
      'ohhssshhho',
      'ohsseSsSho',
      'ohsssssoho',
      '.ossssoo..',
      '..oooo....',
    ];
    return Surface.fromMap(rows, LEGEND);
  }

  function build() {
    if (AI_REQUIRED.every(n => AI_FRAMES[n])) return buildFromAI();
    const frontStand = bake(FRONT);
    const backStand = bake(BACK);
    const dirs = {
      downRight: {
        stand: frontStand,
        blink: bake(blinkFrame(FRONT)),
        walk: [frontStand, bake(stepFrame(FRONT, LEFT_LEG)), frontStand, bake(stepFrame(FRONT, RIGHT_LEG))],
        sit: bake(seatedFrame(FRONT)),
      },
      upRight: {
        stand: backStand,
        blink: backStand,
        walk: [backStand, bake(stepFrame(BACK, LEFT_LEG)), backStand, bake(stepFrame(BACK, RIGHT_LEG))],
        sit: bake(seatedFrame(BACK)),
      },
    };
    dirs.downLeft = mirrorDir(dirs.downRight);
    dirs.upLeft = mirrorDir(dirs.upRight);
    return { dirs, sleepHead: bakeSleepHead(), height: FRONT.length, sitHeight: 21 };
  }

  function mirrorDir(dir) {
    return {
      stand: dir.stand.mirrored(),
      blink: dir.blink.mirrored(),
      walk: dir.walk.map(sf => sf.mirrored()),
      sit: dir.sit.mirrored(),
    };
  }

  return { build, loadOverrides };
})();
